// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddcontributorSlideOver: typeof import('./components/AddcontributorSlideOver.vue')['default']
    AddReviewSlideOver: typeof import('./components/AddReviewSlideOver.vue')['default']
    AddVersionSlideOver: typeof import('./components/AddVersionSlideOver.vue')['default']
    AskReview: typeof import('./components/AskReview.vue')['default']
    CreateRepositorySlideOver: typeof import('./components/CreateRepositorySlideOver.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideOver: typeof import('./components/SlideOver.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
